yolo:
  ros__parameters:
    model_name: yolov8                                                       # "yolov5" or "yolov8"
    model_type: seg                                                          # "det" or "seg"
    engine_path: /home/jetson/Documents/weights/yolov8s-seg.engine
    conf_thres: 0.25
    nms_thres:  0.65
    class_txt: coco.txt
    width: 640
    height: 640
    rgb_topic: /color/color_raw
    depth_topic: /depth/depth_raw
    output_topic: trash_detection/detection