yolo:
  ros__parameters:
    model_name: yolov8
    engine_path: /home/jetson/Documents/tensorrt-ros2/src/stardust_tensorrt/model/yolov8s.engine
    conf_thres: 0.25
    nms_thres:  0.65
    class_num:  80
    rgb_topic: /color/color_raw
    depth_topic: /depth/depth_raw
    output_topic: trash_detection/detection