yolo:
  ros__parameters:
    model_name: yolov8
    model_type: seg
    engine_path: /home/stardust/open_project/YOLOv8-TensorRT/yolov8s-seg.onnx
    conf_thres: 0.25
    nms_thres:  0.65
    class_txt: coco.txt
    width: 640
    height: 640
    rgb_topic: /color/color_raw
    depth_topic: /depth/depth_raw
    output_topic: trash_detection/detection